export const LANGUAGE = {
  'english': {
    'select': 'Select Your Calendar',
    'scroll': 'Scroll down to see more',
    'other': 'Other',
    'open': 'Open',
    'calendar': 'Calendar',
    'clickactions': 'Click Actions',
    'clicksubscribe': 'Click Subscribe to Other Calendars',
    'enterlink': 'Enter the link below, then click Continue.',
    'eventtimeswrong': 'Event times wrong? Verify your',
    'timezone': 'timezone settings',
    'clickyes': 'Click Yes on the popup!',
    'ifnopopup': 'If no popup appears, open',
    'clickopen': 'Click Open Calendar and select From Internet.',
    'enterlink2': 'Enter the link below, then click Ok.',
    'torefresh': 'To refresh the calendar: click on Send/Receive tab and click Send/Receive All Folders',
    'clicklaunch': 'Click Launch on the popup!',
    'clickfile': 'Click File',
    'clicknew': 'Click New Calendar Subscription...',
    'enterlink3': 'Enter the link below, then click Subscribe.',
    'savecalendar': 'Save calendar.',
    'opencalendar': 'Open calendar.',
    'tokeepadding': 'To keep adding all events to the same calendar, enter your email below. Skip this step if you\'re fine with having events adding to separate calendars.',
    'validemail': 'Please enter a valid email.',
    'submit': 'Submit',
    'dontsee': 'Don\'t see it on your phone? Go to',
    'mobilebrowser': 'on your mobile browser and make sure',
    'calendarchecked': 'the calendar is checked',
    'emailme': 'Email me these instructions',
    'poweredby': 'Powered By',
    'allsports': 'All Sports',
    'selectyour': 'Select your',
    'stillproblems': 'Still having problems?',
    'troubleshoot': 'Troubleshoot',
    'welldone': 'Well Done!',
    'addtocalendar': 'ADD TO CALENDAR',
    'allcategories': 'All Categories',
    'choosecategory': 'Choose a Category',
    "chooseCalendar": "Choose a Calendar",
    'syncyahoo': 'Sync With Yahoo',
    'calendardownloaded': 'This calendar has been downloaded',
    'followinstructions': 'Follow these instructions',
    'staticdownload': 'This is a static download. For syncing, please choose one of the other options from the previous screen.',
    'share': 'Share',
    'added': 'Calendar has been added!',
    'view': 'VIEW NOW',
    'copy': 'COPY LINK',
    'also': 'Also, Check out:',
    'downloadcalendar': 'DOWNLOAD CALENDAR',
    'adding': 'Adding to your',
    'download': 'Download the',
    'upcoming': 'View Upcoming Events',
    'sync': 'Sync with',
    'syncmessage': 'Get new events and updates directly in your calendar.',
    'error': 'Oops, something went wrong. Try again. If this persists, shoot us an email at',
    'syncing': 'Syncing',
    'syncingSubHeading': "Going forward, you'll get new events and updates in your calendar.",
    'tvSubHeading': "Why do we need this? So we can include the right channel information in your reminders.",
    'nowShare': 'now share',
    "calendarSynced": "Calendar Synced!",
    "recommendations": "Stanza Recommends",
    "syncGetEvents": "Sync to get events and updates directly in your calendar.",
    "syncCalendarWith": "Sync Calendar With",
    "customizeCalendar": "Customize Your Calendar",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "SKIP",
    "next": "NEXT",
    "syncWith": "Subscribe to",
    "getNewEvents": "Get updates directly in your calendar"
  },
  'french': {
    'select': 'Sélectionnez votre calendrier',
    'scroll': 'Faites défiler pour voir plus',
    'other': 'AUTRE',
    'open': 'Ouvert',
    'calendar': 'Calendrier',
    'clickactions': 'Cliquez sur Actions',
    'clicksubscribe': 'Cliquez sur Abonnez-vous a d\'autres agendas',
    'enterlink': 'Entrez le lien ci-dessous, puis cliquez sur Ok.',
    'eventtimeswrong': 'L\'heure des evenements mal? Verifiez votre',
    'timezone': 'les parametres de fuseau horarie',
    'clickyes': 'Cliquez sur Oui dans la fenetre contextuelle!',
    'ifnopopup': 'Si aucune fenêtre apparaît, ouvrez',
    'clickopen': 'Cliquez sur Ouvrir le calendrier et choisir à partir d\'Internet.',
    'enterlink2': 'Entrez le lien ci-dessous, puis cliquez sur OK.',
    'torefresh': 'Pour actualiser le calendrier: cliquez sur Envoyer / Recevoir onglet et cliquez sur Envoyer / Recevoir tous les dossiers',
    'clicklaunch': 'Cliquez sur Lancer dans la fenêtre contextuelle!',
    'clickfile': 'Cliquez sur Fichier',
    'clicknew': 'Cliquez sur Nouveau Calendrier Abonnement...',
    'enterlink3': 'Entrez le lien ci-dessous, puis cliquez sur Abonnez-vous.',
    'savecalendar': 'Enregistrer calendrier.',
    'opencalendar': 'Ouvrir le calendrier.',
    'tokeepadding': 'Pour continuer à ajouter tous les événements de la même année civile, entrez votre adresse électronique ci-dessous. Passer cette étape si vous êtes très bien d\'avoir des événements en ajoutant des calendriers distincts.',
    'validemail': 'S\'il vous plaît entrer une adresse email valide.',
    'submit': 'Soumettre',
    'dontsee': 'Ne pas le voir sur votre téléphone? Allez à',
    'mobilebrowser': 'sur votre navigateur mobile et assurez-vous',
    'calendarchecked': 'le calendrier est cochée.',
    'emailme': 'Envoyez-moi ces instructions',
    'poweredby': 'Alimenté Par',
    'allsports': 'Toutes Les Sports',
    'selectyour': 'Choisissez votre',
    'stillproblems': 'Encore des problèmes?',
    'troubleshoot': 'Résoudre les problèmes',
    'welldone': 'Bravo!',
    'addtocalendar': 'Ajouter au Calendrier',
    'allcategories': 'Toutes les Catégories',
    'choosecategory': 'Choisir une catégorie',
    'chooseCalendar': 'Choisissez un calendrier',
    'syncyahoo': 'Synchronisation avec Yahoo',
    'calendardownloaded': 'Ce calendrier a été téléchargé',
    'followinstructions': 'Suivez ces instructions',
    'staticdownload': "Ce est un téléchargement statique. Pour la synchronisation , se il vous plaît choisir l'une des autres options de l'écran précédent.",
    'share': 'Part',
    'added': 'Calendrier a été ajoutée!',
    'view': 'VOIR MAINTENANT',
    'copy': 'COPIER LE LIEN',
    'also': 'En outre, vérifiez:',
    'downloadcalendar': 'TÉLÉCHARGER CALENDRIER',
    'adding': 'Ajout à votre',
    'download': 'Télécharger le',
    'upcoming': 'Voir les Prochains Événements',
    'sync': 'Abbonez-vous aux',
    'syncmessage': 'et recevez les dernières mises à jour dans votre calendrier.',
    'error': 'Malheureusement quelque chose a mal tourné. Essayez encore ou envoyez un email a',
    'syncing': 'Synchronisation',
    'syncingSubHeading': "Aller de l'avant , vous obtiendrez de nouveaux événements et mises à jour dans votre calendrier.",
    'tvSubHeading': "Pourquoi avons nous besoin de ça? Donc, nous pouvons inclure les informations de canal droit dans vos rappels.",
    'nowShare': 'maintenant partager',
    "calendarSynced": "Calendrier synchronisé!",
    "recommendations": "Recommandations",
    "syncGetEvents": "Synchroniser pour obtenir des événements et des mises à jour directement dans votre agenda.",
    "syncCalendarWith": "Synchronisez Calendrier Avec",
    "customizeCalendar": "Personnalisez Votre Calendrier",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "PASSER",
    "next": "SUIVANT",
    "syncWith": "Synchronisez avec",
    "getNewEvents": "Obtenez de nouveaux événements et mises à jour directement dans votre agenda"
  },
  'dutch': {
    'select': 'Selecteer jouw kalender',
    'scroll': 'Scroll verder om meer te zien',
    'other': 'Anders',
    'open': 'Openen',
    'calendar': 'Kalender',
    'clickactions': 'Selecteer Acties',
    'clicksubscribe': 'Selecteer Aanmelden voor Andere Kalenders',
    'enterlink': 'Voeg onder de link toe, selecteer dan Volgende.',
    'eventtimeswrong': 'Tijd van evenement verkeerd? Verifieer jouw',
    'timezone': 'Tijdzone instellingen',
    'clickyes': 'Selecteer Ja op de pop-up!',
    'ifnopopup': 'Als er geen pop-up verschijnt, open',
    'clickopen': 'Selecteer Kalender Openen en Selecteer Van Internet.',
    'enterlink2': 'Voeg onder de link toe, selecteer dan OK.',
    'torefresh': 'Om de kalender te verversen: selecteer het verzenden/ontvangen tab en selecteer dan Alle mappen verzenden/ontvangen',
    'clicklaunch': 'Selecteer Uitvoeren op de pop-up!',
    'clickfile': 'Selecteer bestand',
    'clicknew': 'Selecteer Nieuw Kalender Abonnement...',
    'enterlink3': 'Voeg de link toe en selecteer dan abonneren.',
    'savecalendar': 'Sla kalender op.',
    'opencalendar': 'Open kalender.',
    'tokeepadding': 'Laat hier je e-mail achter om alle evenementen aan dezelfde kalender toe te blijven voegen. Sla deze stap over als je geen probleem hebt met het toevoegen van evenementen aan gescheiden kalenders.',
    'validemail': 'Vul een geldig e-mailadres in.',
    'submit': 'Verzenden',
    'dontsee': 'Niet te zien op je telefoon? Ga naar',
    'mobilebrowser': 'in je mobiele browser en zorg ervoor',
    'calendarchecked': 'de kalender is gecontroleerd',
    'emailme': 'E-mail mij deze instructies',
    'poweredby': 'Mogelijk gemaakt door',
    'allsports': 'Alle sporten',
    'selectyour': 'Selecteer jouw',
    'stillproblems': 'Ervaar je nog steeds problemen?',
    'troubleshoot': 'Veel gestelde vragen',
    'welldone': 'Goed gedaan!',
    'addtocalendar': 'Voeg toe aan kalender',
    'allcategories': 'Alle categorieën',
    'choosecategory': 'Selecteer een categorie',
    'chooseCalendar': 'Kies een taal',
    'syncyahoo': 'Synchroniseer met Yahoo',
    'calendardownloaded': 'Deze kalender is gedownload',
    'followinstructions': 'Volg deze instructies',
    'staticdownload': 'Dit is een statische download. Kies alsjeblieft voor één van de andere opties van het vorige scherm om te kunnen synchroniseren.',
    'share': 'Deel',
    'added': 'Kalender is toegevoegd!',
    'view': 'BEKIJK NU',
    'copy': 'KOPIEER LINK',
    'also': 'Bekijk ook:',
    'downloadcalendar': 'DOWNLOAD KALENDER',
    'adding': 'Toe te voegen aan je',
    'download': 'Download de',
    'upcoming': 'Zie aankomende evenementen',
    'sync': 'Synchroniseer met',
    'syncmessage': 'Ontvang nieuwe evenementen en updates direct in je kalender.',
    'error': 'Helaas ging er iets mis . Probeer opnieuw. Als dit aanhoudt, stuur ons een e-mail op',
    'syncing': 'Synchroniseren',
    'syncingSubHeading': "Krijg je nieuwe evenementen en updates in uw agenda.",
    'tvSubHeading': "Waarom hebben we dit nodig? Zo kunnen we onder meer het juiste kanaal informatie in uw herinneringen.",
    'nowShare': 'nu delen',
    "calendarSynced": "Agenda Gesynchroniseerd!",
    "recommendations": "Aanbevelingen",
    "syncGetEvents": "Synchroniseer op gebeurtenissen en updates rechtstreeks in uw agenda te krijgen.",
    "syncCalendarWith": "Synchroniseer Agenda Met",
    "customizeCalendar": "Pas uw agenda",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "SLA",
    "next": "VOLGENDE",
    "syncWith": "Synchroniseer met",
    "getNewEvents": "Ontvang nieuwe evenementen en updates rechtstreeks in uw agenda"
  },
  'italian': {
    'select': 'Seleziona il tuo Calendario',
    'scroll': 'Scorri verso il basso per vedere di più',
    'other': 'Altro',
    'open': 'Apri',
    'calendar': 'Calendario',
    'clickactions': 'Clicca Azioni',
    'clicksubscribe': 'Clicca Iscriviti per Altre Azioni',
    'enterlink': 'Inserisci il seguente link e poi clicca Continua.',
    'eventtimeswrong': 'Orari dell\'evento sbagliati? Verifica il tuo',
    'timezone': 'Configuarazione del fuso orario',
    'clickyes': 'Clicca Si sul pop-up!',
    'ifnopopup': 'Se il pop-up non appare, apri',
    'clickopen': 'Clicca Apri Calendario e seleziona Da Internet.',
    'enterlink2': 'Inserisci il seguente link e poi clicca Ok.',
    'torefresh': 'Per aggiornare il calendario: clicca su Invia/Ricevi Tutte le Cartelle',
    'clicklaunch': 'Clicca Avvia sul pop-up!',
    'clickfile': 'Clicca File',
    'clicknew': 'Clicca Iscrizione Nuovo Calendario...',
    'enterlink3': 'Inserisci il seguente link e clicca Iscriviti.',
    'savecalendar': 'Salva il calendario.',
    'opencalendar': 'Apri il calendario.',
    'tokeepadding': 'Per aggiungere tutti gli eventi allo stesso calendario inserisci la tua email qui sotto. Salta questo punto se va bene avere gli eventi in calendari separati.',
    'validemail': 'Per favore, inserire una email valida.',
    'submit': 'Inscriviti',
    'dontsee': 'Non lo vedi sul tuo cellulare? Vai a ',
    'mobilebrowser': 'isul tuo browser e assicurati che',
    'calendarchecked': 'il calendario è stato controllato',
    'emailme': 'Inviami per email queste istruzioni',
    'poweredby': 'Offerto da',
    'allsports': 'Tutti gli sport',
    'selectyour': 'Seleziona il tuo',
    'stillproblems': 'Hai ancora problemi?',
    'troubleshoot': 'Risolvi i problemi',
    'welldone': 'Ben fatto!',
    'addtocalendar': 'Aggiungi al Calendario',
    'allcategories': 'Tutte le Categorie',
    'choosecategory': 'Scegli una Categoria',
    'syncyahoo': 'Sincronizzati con Yahoo',
    'calendardownloaded': 'Questo calendario è stato scaricato',
    'followinstructions': 'VSegui queste istruzioni',
    'staticdownload': 'Questo è un downlaod static. Per sicronizzare per favore seleziona una delle seguenti opzioni dalla schermata precedente.',
    'share': 'Condividi',
    'added': 'Il Calendario è stato aggiunto!',
    'view': 'VEDI ORA',
    'copy': 'COPIA IL LINK',
    'also': 'Esci pure:',
    'downloadcalendar': 'SCARICA IL CALENDARIO',
    'adding': 'Aggiungendo al tuo',
    'download': 'Scarica il',
    'upcoming': 'Vedi eventi in arrivo',
    'sync': 'Sincronizzati con',
    'syncmessage': 'Ricevi tutti gli aggiornamenti sulle eventi direttamente sul tuo calendario.',
    'error': 'Sfortunatamente qualcosa è andato storto. Prova ancora. Se ciò persiste inviaci una email a',
    'syncing': 'Sincronizzazione',
    'syncingSubHeading': "Andando avanti, ricevi tutti gli aggiornamenti sulle eventi direttamente sul tuo calendario.",
    'tvSubHeading': "perché ne abbiamo bisogno? Così possiamo comprendere le informazioni canale destro nei vostri ricordi.",
    'nowShare': 'ora condividere',
    "calendarSynced": "Calendario Sincronizzato!",
    "recommendations": "Raccomandazioni",
    "syncGetEvents": "Sincronizzati e ricevi tutti gli aggiornamenti sulle eventi direttamente sul tuo calendario.",
    "chooseCalendar": "Scegliere un calendario",
    "syncCalendarWith": "Sincronizza Calendario Con",
    "customizeCalendar": "Personalizza il tuo calendario",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "SALTARE",
    "next": "IL PROSSIMO",
    "syncWith": "Sincronizzati con",
    "getNewEvents": "Ricevi tutti gli aggiornamenti sulle eventi direttamente sul tuo calendario"
  },
  'russian': {
    'select': 'Выберите ваш календарь',
    'scroll': 'Прокрутите вниз чтобы увидеть больше',
    'other': 'Прочие',
    'open': 'Открыть',
    'calendar': 'Календарь',
    'clickactions': 'Щелкните действия',
    'clicksubscribe': 'Щелкните Подписаться на Другие Календари',
    'enterlink': 'Введите ссылку ниже, потом щелкните продолжить.',
    'eventtimeswrong': 'Время события не правильно? Проверьте ваше',
    'timezone': 'Настройка часового пояса',
    'clickyes': 'Щелкните Да на всплывающем окне!',
    'ifnopopup': 'Если всплывающее окно не появляется, откройте',
    'clickopen': 'Щелкните Открыть Календарь и выберете Из Интернета.',
    'enterlink2': 'Введите ссылку ниже, потом щелкните Окэй.',
    'torefresh': 'Чтобы обновить календарь: щелкните на вкладку Послать/Получить и щелкните Послать/Получить Все Папки',
    'clicklaunch': 'Щелкните Запустить на всплывающем окне!',
    'clickfile': 'Щелкните Файл',
    'clicknew': 'Щелкните Новоя Подписка на Календарь...',
    'enterlink3': 'Введите ссылку ниже, потом щелкните Подписаться.',
    'savecalendar': 'Сохранить календарь.',
    'opencalendar': 'Открыть календарь.',
    'tokeepadding': 'Чтобы продолжить вводить все события в тот же календарь, введите адрес электронной почты ниже. Пропустите этот шаг, если вы хотите вводить события в отдельные календари.',
    'validemail': 'Пожалуйста, введите действительный адрес электронной почты.',
    'submit': 'Представить',
    'dontsee': 'Если вы не видите ето на своем телефоне, идите к ',
    'mobilebrowser': 'на вашем мобильном браузере и проверьте что',
    'calendarchecked': 'календарь отмечен',
    'emailme': 'Пошлите мне эти инструкции по электронной почте',
    'poweredby': 'Сделано возможным',
    'allsports': 'Все Виды Спорта',
    'selectyour': 'Выберите ваше',
    'stillproblems': 'Тем не менее проблемы?',
    'troubleshoot': 'Устранение проблем',
    'welldone': 'Отлично сработано!',
    'addtocalendar': 'Добавить в Календарь',
    'allcategories': 'Все Категории',
    'choosecategory': 'Выберите Категорию',
    'chooseCalendar': 'Выберите календарь',
    'syncyahoo': 'Синхронизировать с Yahoo',
    'calendardownloaded': 'Этот календарь был загружен',
    'followinstructions': 'Следуйте инструкциям',
    'staticdownload': ' Это статическая загрузка. Для синхронизации, выберите один из других вариантов из предыдущего экрана.',
    'share': 'Делиться',
    'added': 'Календарь был добавлен!',
    'view': 'ПРОСМОТРЕТЬ',
    'copy': 'КОПИРОВАТЬ ССЫЛКУ',
    'also': 'Кроме того, проверьте:',
    'downloadcalendar': 'СКАЧАТЬ КАЛЕНДАРЬ',
    'adding': 'Добавление в',
    'download': 'Скачать',
    'upcoming': 'Просматривать предстоящие события',
    'sync': 'Синхронизации',
    'syncmessage': 'Получать новые события и обновления прямо в календаре.',
    'error': 'К сожалению, что-то пошло не так. Попробуйте еще раз. Если все равно не удается, отправьте нам электронное письмо на',
    'syncing': 'Cинхронизации',
    "syncingSubHeading": "Забегая вперед, вы получите новые события и обновления в вашем календаре.",
    'tvSubHeading': "Почему нам это надо? Таким образом, мы можем включать в себя информацию правого канала в ваших напоминаний.",
    'nowShare': "в настоящее время доля",
    "calendarSynced": "Календарь Синхронизировано!",
    "recommendations": "Pекомендации",
    "syncGetEvents": "Синхронизация , чтобы получить события и обновления непосредственно в календаре.",
    "syncCalendarWith": "Синхронизация календаря с",
    "customizeCalendar": "Настроить календарь",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "Nропускать",
    "next": "СЛЕДУЮЩИЙ",
    "syncWith": "Синхронизация с",
    "getNewEvents": "Получать новые события и обновления непосредственно в календаре"
  },
  'portuguese': {
    'select': 'Selecione seu calendário',
    'scroll': 'Desça a página para ver mair',
    'other': 'Outro',
    'open': 'Abrir',
    'calendar': 'Calendário',
    'clickactions': 'clique ações',
    'clicksubscribe': 'Clique Se Inscrever em Outro Calendário',
    'enterlink': 'Entre no link abaixo, depois clique em Continuar.',
    'eventtimeswrong': 'O horário do evento está errado? Verifique o seu',
    'timezone': 'Configurações de fuso horário',
    'clickyes': 'Clique Sim no Pop Up!',
    'ifnopopup': 'Caso nenhum Pop up aparecer, abrir',
    'clickopen': 'Clique em Abrir calendário e selecione Da internet.',
    'enterlink2': 'Entre no link abaixo e clique Ok.',
    'torefresh': 'Para atualizar o calendário, cliquem em Enviar/Receber e clique em Enviar/Receber todas as pastas',
    'clicklaunch': '', //this one was missing from the translation but isn't in use
    'clickfile': 'Clique arquivo',
    'clicknew': 'Clique inscrever novo calendário...',
    'enterlink3': 'Entre no link abaixo e depois clique em Inscrever.',
    'savecalendar': 'Salvar calendário.',
    'opencalendar': 'abrir calendário.',
    'tokeepadding': 'Para continuar adicionando todos os eventos no mesmo calendário, insira teu e-mail abaixo.  Pule esta etapa se você não se importar em continuar adicionando eventos em calendários separados.',
    'validemail': 'Por favor, insira um e-mail válido.',
    'submit': 'enviar',
    'dontsee': 'Não vê no seu celular? vá para ',
    'mobilebrowser': 'No seu navegador do celular e certifique-se de que',
    'calendarchecked': 'o calendário está marcado',
    'emailme': 'Me envie por e-mail essas instruções',
    'poweredby': 'Criado por',
    'allsports': 'Todos os esportes',
    'selectyour': 'Selecione o seu',
    'stillproblems': 'Ainda está tendo problemas?',
    'troubleshoot': 'Solucionar problemas',
    'welldone': 'Bem feito!',
    'addtocalendar': 'Adicionar no Calendário',
    'allcategories': 'Todas categorias',
    'choosecategory': 'Escolher categoria',
    'chooseCalendar': 'Escolha um calendário',
    'syncyahoo': 'Sicronizar com Yahoo',
    'calendardownloaded': 'O download deste calendário foi feito',
    'followinstructions': 'Siga essas instruções',
    'staticdownload': 'Este é um download estático. Para sicronizar, por favor, selecione uma das opções da tela anterior.',
    'share': 'Compartilhar',
    'added': 'Calendário foi adicionado!',
    'view': 'VER AGORA',
    'copy': 'COPIAR LINK',
    'also': 'Além disso, confira:',
    'downloadcalendar': 'BAIXE O CALENDÁRIO',
    'adding': 'Adicionar ao seu',
    'download': 'Baixe o',
    'upcoming': 'Ver próximos eventos',
    'sync': 'Sicronizar com',
    'syncmessage': 'Obter novo evento e atualize diretamento no seu calendário.',
    'error': 'Opps, algo de errado ocorreu. Tente novamente. Se persistir, nos mande um e-mail',
    'syncing': 'Sincronizar',
    "syncingSubHeading": "Daqui para frente, você vai ter novos eventos e atualizações em seu calendário.",
    'tvSubHeading': "Por que nós precisamos disso? Assim, podemos incluir a informação do canal direito em suas lembranças.",
    "nowShare": "agora compartilhar",
    "calendarSynced": "Calendário Sincronizado!",
    "recommendations": "Recomendações",
    "syncGetEvents": "Sync para obter eventos e atualizações diretamente no seu calendário.",
    "syncCalendarWith": "Sincronizar Calendário Com",
    "customizeCalendar": "Personalize seu calendário",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "IGNORAR",
    "next": "PROXIMO",
    "syncWith": "Sincronizar com",
    "getNewEvents": "Obter novos eventos e atualizações diretamente no seu calendário"
  },
  'german': {
    'select': 'Wähle Deinen Kalender',
    'scroll': 'Scrolle herunter um mehr zu sehen',
    'other': 'Andere',
    'open': 'Öffnen',
    'calendar': 'Kalender',
    'clickactions': 'Klicke auf Aktionen',
    'clicksubscribe': 'Klicke auf Andere Kalender abonieren',
    'enterlink': 'Gebe den Link unten ein, dann klicke auf Fortsetzen.',
    'eventtimeswrong': 'Ereigniszeit falsch? Überprüfe Deine',
    'timezone': 'Zeitzoneneinstellungen',
    'clickyes': 'Klicke Ja im Popup!',
    'ifnopopup': 'Wenn kein Popup erscheint, öffne',
    'clickopen': 'Klicke Kalender Öffnen und wähle Vom Internet.',
    'enterlink2': 'Gebe den Link unten ein, dann klicke auf OK.',
    'torefresh': 'Um den Kalender zu aktualisiern: Klicke auf den Senden/Empfangen Tab und klicke Senden/Empfangen alle Ordner',
    'clicklaunch': 'Klicke Starten im Pop-up!',
    'clickfile': 'Klicke Datei',
    'clicknew': 'Klicke Neues Kalenderabonnenment...',
    'enterlink3': 'Gebe den Link unten ein, dann klicke auf Abonnieren.',
    'savecalendar': 'Kalender speichern.',
    'opencalendar': 'Kalender öffnen.',
    'tokeepadding': 'Um weiterhin alle Ereignisse zum selben Kalender hinzuzufügen, gebe Deine E-Mail Adresse unten ein. Überspringe diesen Schritt wenn Du Ereignisse in separate Kalender hinzufügen willst.',
    'validemail': 'Bitte gebe eine korrekte E-Mail Adresse ein.',
    'submit': 'Abschicken',
    'dontsee': 'Siehst du es nicht auf deinem Handy? Gehe zu',
    'mobilebrowser': 'in Deinem mobilen Browser und stelle sicher, dass',
    'calendarchecked': 'der Kalender ausgewählt ist.',
    'emailme': 'Sende mir diese Anweisungen zu',
    'poweredby': 'Powered By',
    'allsports': 'Alle Sportarten',
    'selectyour': 'Wähle Deine',
    'stillproblems': 'Hast Du immer noch Probleme?',
    'troubleshoot': 'Fehler suchen',
    'welldone': 'Gut gemacht!',
    'addtocalendar': 'Zum Kalender hinzufügen',
    'allcategories': 'Alle Kategorien',
    'choosecategory': 'Wähle eine Kategorie',
    "chooseCalendar": "Wähle einen Kalender",
    'syncyahoo': 'Mit Yahoo synchronisieren',
    'calendardownloaded': 'Dieser Kalender wurde heruntergeladen',
    'followinstructions': 'Folge diesen Anweisungen',
    'staticdownload': 'Das ist ein statischer Download. Zum synchronisieren, wähle bitte eine der anderen Optionen von der vorherigen Maske.',
    'share': 'Teilen',
    'added': 'Kalender wurde hinzugefügt!',
    'view': 'JETZT ANSEHEN',
    'copy': 'LINK KOPIEREN',
    'also': 'Schau Dir auch an:',
    'downloadcalendar': 'KALENDAR HERUNTERLADEN',
    'adding': 'Zu Deiner hinzufügen',
    'download': 'Den herunterladen',
    'upcoming': 'Bevorstehende Ereignisse anschauen',
    'sync': 'Mit synchronisieren',
    'syncmessage': 'Hol dir neue Ereignisse und Aktualisierungen direkt in deinen Kalender.',
    'error': 'Leider ist etwas schief gelaufen. Versuche es erneut. Wenn der Fehler weiterhin besteht, sende uns eine E-Mail.',
    'syncing': 'Synchronisieren',
    'syncingSubHeading': "In der Zukunft wirst du neue Ereignisse und Aktualisierunen in deinen Kalender erhalten.",
    'tvSubHeading': "Warum brauchen wir das? Damit wir die richtigen Kanalinformationen Deinen Erinnerungen beifügen können.",
    'nowShare': 'jetzt teilen',
    "calendarSynced": "Kalender synchronisiert!",
    "recommendations": "Empfehlungen",
    "syncGetEvents": "Synchronisieren um Ereignisse und Updates direkt in Deinem Kalender zu erhalten.",
    "syncCalendarWith": "Kalender mit synchronisieren",
    "customizeCalendar": "Deinen Kalender anpassen",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "ÜBERSPRINGEN",
    "next": "NÄCHSTE",
    "syncWith": "Synchronisieren mit",
    "getNewEvents": "Hol dir neue Ereignisse und Aktualisierungen direkt in deinen Kalender."
  },
  'greek': {
    'select': 'Διαλεξτε το ημερολογιό σας',
    'scroll': 'Κατεβείτε προς τα κάτω για να δείτε περισσότερα',
    'other': 'Άλλα',
    'open': 'Ανοίξτε',
    'calendar': 'Ημερολόγιο',
    'clickactions': 'Κάντε κλικ',
    'clicksubscribe': 'Πατήστε εγγραφή σε άλλα ημερολόγια',
    'enterlink': 'Βάλτε το παρακάτω λινκ και πατήστε συνέχεια',
    'eventtimeswrong': 'Λάθος ώρα εκδήλωσης; Επαληθευστε τις σωστές',
    'timezone': 'Ρυθμίσεις ζώνης ώρας',
    'clickyes': 'Πατήστε "ναι" στο αναδιόμενο παράθυρο',
    'ifnopopup': 'Εάν το αναδιόμενο παράθυρο δεν ανοίγει, πατήστε "άνοιξε"',
    'clickopen': 'Πατήστε "άνοιξε το ημερολόγιο" και επιλέξτε "Από το Ίντερνετ"',
    'enterlink2': 'Εισάγετε το παρακάτω λινκ και στη συνέχεια πατήστε "ΟΚ"',
    'torefresh': 'Για να ανανεώσετε το ημερολόγιο: Πατήστε τη καρτέλα αποστολή/παραλαβή και έπειτα Αποστολή/Παραλαβή σε όλους τους φακέλους.',
    'clicklaunch': 'Πατήστε άνοιγμα στο αναδιόμενο παράθυρο',
    'clickfile': 'Πατήστε το αρχείο',
    'clicknew': 'Klicke Neues Kalenderabonnenment...',
    'enterlink3': 'Gebe den Link unten ein, dann klicke auf Abonnieren.',
    'savecalendar': 'Αποθήκευση ημερολογίου.',
    'opencalendar': 'Ανοίξτε το ημερολόγιο.',
    'tokeepadding': 'Για να προσθέσετε όλες τις εκδηλώσεις εισάγετε το παρακάτω email. προσπεράστε αυτό το βήμα εάν δεν σας πειράζει να έχετε εκδηλώσεις σε διαφορετικούς φακέλους.',
    'validemail': 'Παρακαλώ βάλτε έγκυρο email.',
    'submit': 'Υποβολή',
    'mobilebrowser': 'Στο πρόγραμμα περιήγησης του κινητού σας και βεβαιώστε',
    'calendarchecked': 'Το ημερολόγιο ειναι ελεγμένο.',
    'emailme': 'Στείλτε μου τις οδηγίες με email',
    'poweredby': 'Χορηγούμενο από',
    'allsports': 'Όλα τα αθλήματα',
    'selectyour': 'Διαλέξτε το δικό σας',
    'stillproblems': 'Ακόμα αντιμετωπίζετε προβλήματα?',
    'troubleshoot': 'Αντιμετώπιση προβλήματος',
    'welldone': 'Καλή δουλειά!',
    'addtocalendar': 'Προσθέστε στο ημερολόγιο',
    'allcategories': 'Όλες οι κατηγορίες',
    'choosecategory': 'Διαλέξτε κατηγορία',
    "chooseCalendar": "Διαλέξτε ημερολόγιο",
    'syncyahoo': 'Συγχρονισμός με το Yahoo',
    'calendardownloaded': 'Το ημερολόγιο κατέβηκε',
    'followinstructions': 'Ακολουθείστε τις οδηγίες',
    'staticdownload': 'Αυτή είναι στατική λήψη. Για συγχρονισμό παρακαλώ διαλέξτε μία από τις δύο επιλογές από την προηγούμενη οθόνη.',
    'share': 'Μοιραστείτε',
    'added': 'Το ημερολόγιο προσθέτικε',
    'view': 'Δείτε τώρα',
    'copy': 'Αντιγράψτε το λινκ',
    'also': 'Επίσης, δείτε αυτό:',
    'downloadcalendar': 'Κατεβάστε το ημερολόγιο',
    'adding': 'Προσθέστε το δικό σας',
    'download': 'Κατεβάστε το αρχείο',
    'upcoming': 'Δείτε τις ανερχόμενες εκδηλώσεις',
    'sync': 'Συγχρονισμός με',
    'syncmessage': 'Λάβετε καινούργιες εκδηλώσεις και αναβαθμίσεις κατευθείαν στο ημερολόγιό σας.',
    'error': 'Δυστυχώς κάτι πήγε στραβά. προσπαθήστε ξανά. Εάν το πρόβλημα συνεχίζεται, στείλτε μας email στο.',
    'syncing': 'Συγχρονισμός',
    'syncingSubHeading': "Πηγαίνοντας μπροστά, θα χρειαστείτε καινούργιες εκδηλώσεις και αναβαθμίσεις στο ημερολόγιό σας.",
    'tvSubHeading': ".",
    'nowShare': 'Τώρα μοιραστείτε',
    "calendarSynced": "Το ημερολόγιο συγχρονίστηκε",
    "recommendations": "Συστάσεις",
    "syncGetEvents": "Συγχρονίστε για να λαμβάνετε εκδηλώσεις και αναβαθμίσεις κατευθείαν στο ημερολόγιο σας.",
    "syncCalendarWith": "Συγχρονισμός του ημερολογίου με",
    "customizeCalendar": "Προσαρμογή του ημερολογίου",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "Προσπεράστε",
    "next": "Επόμενο",
    "syncWith": "Συγχρονισμός με",
    "getNewEvents": "Λάβετε νέες εκδηλώσεις και ενημερώσεις απευθείας στο ημερολόγιό σας"
  },
  'polish': {
    'select': 'Wybierz swój kalendarz',
    'scroll': 'Przewiń w dół, żeby zobaczyć więcej',
    'other': 'Inny',
    'open': 'Otwórz',
    'calendar': 'Kalendarz',
    'clickactions': 'Naciśnij Działania',
    'clicksubscribe': 'Naciśnij Subskrybuj do Innych Kalendarzy',
    'enterlink': 'Wejdź w poniższy link, następnie naciśnij Kontynuuj.',
    'eventtimeswrong': 'Zły czas wydarzenia? Zweryfikuj swój',
    'timezone': 'ustawienia strefy czasowej',
    'clickyes': 'Naciśnij Tak na wyskakującym okienku!',
    'ifnopopup': 'Jeśli nie pojawi się oknienko, otwórz',
    'clickopen': 'Naciśnij Otwórz Kalendarz i wybierz Z Internetu.',
    'enterlink2': 'Wejdź w poniższy link, następnie naciśnij Ok.',
    'torefresh': 'Aby odświeżyć kalendarz: naciśnij Wyślij/Odbierz i kliknij Wyślij/Odbierz Wszystkie Foldery',
    'clicklaunch': 'Naciśnij Uruchom na wyskakującym okienku!',
    'clickfile': 'Naciśnij Plik',
    'clicknew': 'Naciśnij Subskrypcja Nowego Kalendarza...',
    'enterlink3': 'Wejdź w poniższy link, następnie naciśnij Subskrybuj.',
    'savecalendar': 'Zapisz kalendarz.',
    'opencalendar': 'Otwórz kalendarz.',
    'tokeepadding': 'Aby dodać wszystkie zdarzenia do tego samego kalendarza, wprowadź adres email poniżej. Pomiń ten krok, jeśli nie przeszkadza Ci dodawanie wydarzeń do oddzielnych kalendarzy.',
    'validemail': 'Podaj prawidłowy email.',
    'submit': 'Zgłoś',
    'dontsee': 'Nie widzisz tego na swoim telefonie? Idź do',
    'mobilebrowser': 'na Twojej przeglądarce w telefonie i upewnij się',
    'calendarchecked': 'Kalendarz jest sprawdzony',
    'emailme': 'Wyślij mi te instrukcje mailem',
    'poweredby': 'Zasilany przez',
    'allsports': 'Wszystkie sporty',
    'selectyour': 'Wybierz swój kalendarz',
    'stillproblems': 'Ciągle masz problemy?',
    'troubleshoot': 'Rozwiązania',
    'welldone': 'Dobra robota!',
    'addtocalendar': 'Dodaj do kalendarza',
    'allcategories': 'Wszystkie kategorie',
    'choosecategory': 'Wybierz kategorie',
    "chooseCalendar": "Wybierz kalendarz",
    'syncyahoo': 'Zsynchronizuj z Yahoo',
    'calendardownloaded': 'Ten kalendarz został ściągnięty',
    'followinstructions': 'Postępuj zgodnie z instrukcją',
    'staticdownload': 'Jest to pobieranie statyczne. Do synchronizacji, wybierz jedną z pozostałych opcji z poprzedniego ekranu.',
    'share': 'Podziel się',
    'added': 'Kalendarz został dodany',
    'view': 'Zobacz teraz',
    'copy': 'Skopiuj hiperłącze',
    'also': 'sprawdź także:',
    'downloadcalendar': 'ściągnij kalendarz',
    'adding': 'dodaj do swoich',
    'download': 'ściągnij kalendarz',
    'upcoming': 'Zobacz nadchodzące wydarzenia',
    'sync': 'Synchronizuj z',
    'syncmessage': 'Pobierz nowe zdarzenia i aktualizacje bezpośrednio w kalendarzu.',
    'error': 'Niestety, cos poszło nie tak. Spróbuj jeszcze raz. Jeśli to si powtórzy, wyślij Nam maila.',
    'syncing': 'Synchronizuję',
    'syncingSubHeading': "Idąc dalej, dostaniesz nowe zdarzenia i aktualizacje w kalendarzu.",
    'tvSubHeading': "Dlaczego tego potrzebujemy? Abyśmy mogli zawrzeć właściwe kanały informacji w Twoich przypomnieniach.",
    'nowShare': 'teraz podziel się',
    "calendarSynced": "Kalendarz został zsynchronizowany!",
    "recommendations": "Zalecenia",
    "syncGetEvents": "Synchronizuj aby otrzymać zdarzenia i zaktualizować bezpośrednio w Twoim kalendarzu.",
    "syncCalendarWith": "Zschynchronizuj kalendarz z",
    "customizeCalendar": "Dostosuj swój kalendarz",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "pomiń",
    "next": "następny",
    "syncWith": "Zschynchronizuj z",
    "getNewEvents": "Pobierz nowe zdarzenia i aktualizacje bezpośrednio w kalendarzu"
  },
  'czech': {
    'select': 'Vyber si svůj kalendář',
    'scroll': 'Niže zjistíš víc',
    'other': 'Jiné',
    'open': 'Otevřít',
    'calendar': 'Kalendář',
    'clickactions': 'Klikni na Akce',
    'clicksubscribe': 'Klikni na Stáhnout si jiné kalendáře',
    'enterlink': 'Vlož adresu a klikni na Pokračovat',
    'eventtimeswrong': 'Jsou časy událostí špatně? Zkontroluj své',
    'timezone': 'nastavení časového pásma',
    'clickyes': 'Ve vyskakovacím okně klikni na Ano',
    'ifnopopup': 'Pokud se vyskakovací okno neobjeví, otevři',
    'clickopen': 'Klikni na Otevřít kalendář a pak Ok',
    'enterlink2': 'Vlož adresu a klikni na Ok',
    'torefresh': 'Pro obnovení kalendáře klikni na Poslat/Přijmout a vyber možnost Poslat/Přijmout všechny složky.',
    'clicklaunch': 'Ve vyskakovacím okně klikni na Spustit',
    'clickfile': 'Klikni na Soubor',
    'clicknew': 'Klikni na Stažení nového kalendáře...',
    'enterlink3': 'Vlož adresu a klikni na Stáhnout.',
    'savecalendar': 'Uložit kalendář.',
    'opencalendar': 'Otevřít kalendář.',
    'tokeepadding': 'Aby bylo možné přidat všechny události do stejného kalendáře, vložte svůj email. Tento krok přeskočte, pokud vám přidávání událostí do různých kalendářů nevadí.',
    'validemail': 'Prosím vložte email ve správném formátu.',
    'submit': 'Potvrdit',
    'dontsee': 'Není vidět na mobilním telefonu? Zkontroluj',
    'mobilebrowser': 've vašem mobilním prohlížeči a ujisti se',
    'calendarchecked': 'že je kalendář zaškrtnutý.',
    'emailme': 'Chci instrukce do emailu',
    'poweredby': 'Za podpory',
    'allsports': 'Všechny sporty',
    'selectyour': 'Vyber',
    'stillproblems': 'Problémy přetrvávají?',
    'troubleshoot': 'Řešení potíží',
    'welldone': 'Skvěle!',
    'addtocalendar': 'Přidat do kalendáře',
    'allcategories': 'Všechny kategorie',
    'choosecategory': 'Vybrat kategorii',
    'syncyahoo': 'Synchronizovat s Yahoo',
    'calendardownloaded': 'Kalendář byl stažen',
    'followinstructions': 'Pokračuj podle instrukcí',
    'staticdownload': 'Toto je statický download. Pro synchronizování prosím vyberte jednu z dalších možností na předchozí obrazovce.',
    'share': 'Sdílet',
    'added': 'Kalendář byl stažen!',
    'view': 'PROHLÉDNOUT',
    'copy': 'KOPÍROVAT LINK',
    'also': 'Podívejte se také na:',
    'downloadcalendar': 'STÁHNOUT KALENDÁŘ',
    'adding': 'Přidávám do vašeho',
    'download': 'Stáhnout',
    'upcoming': 'Zobrazit nadcházející zápasy',
    'sync': 'Zůstaň v kontaktu s klubem',
    'syncmessage': 'Stáhni si všechny zápasy a aktualizace přímo do svého kalendáře.',
    'error': 'Bohužel, něco se pokazilo. Zkuste to znovu, prosím. Pokud bude problém přetrvávat, kontaktujte nás emailem na',
    'syncing': 'Synchronizuji',
    'syncingSubHeading': "Odteď najdete zápasy s aktuálními daty ve svém kalendáři.",
    'tvSubHeading': "Proč to potřebjeme? Chceme pro vaše upozornění využít ty správné informace.",
    'nowShare': 'nyní sdílet',
    "calendarSynced": "Kalendář synchronizován!",
    "recommendations": "Doporučení",
    "syncGetEvents": "Synchronizujte zápasy se svým kalendářem.",
    "chooseCalendar": "Vyberte si kalendář",
    "syncCalendarWith": "Vyberte si",
    "customizeCalendar": "Přispůsobte si váš kalendář",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "PŘESKOČIT",
    "next": "DALŠÍ",
    "syncWith": "Slaďte si svůj kalendář se zápasy",
    "getNewEvents": "Získejte všechna utkání prvního týmu do svého vlastního kalendáře"
  },
  'danish': {
    'select': 'Vælg Kalender',
    'scroll': 'Scroll ned for at se mere',
    'other': 'Andet',
    'open': 'Åben',
    'calendar': 'Kalender',
    'clickactions': 'Tryk på handlinger',
    'clicksubscribe': 'Tryk på abonnér på andre kalendre',
    'enterlink': 'Indsæt link nedenunder, tryk så fortsæt',
    'eventtimeswrong': 'Forkerte begivenhedstider? Bekræft dine',
    'timezone': 'Tidszone indstillinger',
    'clickyes': 'Tryk Ja i popup-vinduet',
    'ifnopopup': 'Hvis der ikke kommer et popup-vindue, åben',
    'clickopen': 'Klik Åben Kaldender og vælg fra internet',
    'enterlink2': 'Insæt link nedenunder, tryk så OK',
    'torefresh': 'For at opdatere kalenderen: tryk på send/modtag knap og tryk send/modtag alle mapper.',
    'clicklaunch': 'Tryk Start i Popup-vinduet',
    'clickfile': 'Tryk på Filer',
    'clicknew': 'Tryk på nyt kalender abonnement...',
    'enterlink3': 'Indsæt link nedenunder, tryk så abonnér.',
    'savecalendar': 'Gem kalender.',
    'opencalendar': 'Åben kalender.',
    'tokeepadding': 'For fortsat at tilføje begivenheder til samme kalender, indsæt din email nedenunder. Spring dette trin over, hvis du er tilfreds med at begivenheder tilføjes seperate kalendre.',
    'validemail': 'Indsæt gyldig email-adresse.',
    'submit': 'Indsend',
    'dontsee': 'Kan du ikke se noget på din telefon? Gå til',
    'mobilebrowser': 'Browseren på din mobil og sikre dig',
    'calendarchecked': 'Kalenderen er tjekket.',
    'emailme': 'Email instruktionerne til mig',
    'poweredby': 'Sponsoreret af',
    'allsports': 'Al sport',
    'selectyour': 'Vælg dit',
    'stillproblems': 'Problémy přetrvávají?',
    'troubleshoot': 'Problemsøgning',
    'welldone': 'Godt klaret!',
    'addtocalendar': 'Tilføj til kalender',
    'allcategories': 'Alle kategorier',
    'choosecategory': 'Vælg kategori',
    "chooseCalendar": "Vælg Kalender",
    'syncyahoo': 'Synkroniser med Yahoo',
    'calendardownloaded': 'Kalenderen er hentet',
    'followinstructions': 'Følg intstruktionerne',
    'staticdownload': 'Denne download er statisk. For synkronisering, vælg en anden mulighed fra forrige billede.',
    'share': 'Del',
    'added': 'Kalenderen er tilføjet!',
    'view': 'SE NU',
    'copy': 'KOPIER LINK',
    'also': 'Se også:',
    'downloadcalendar': 'HENT KALENDER',
    'adding': 'Tilføjer dine',
    'download': 'Hent',
    'upcoming': 'Se kommende begivenheder',
    'sync': 'Synkroniser med',
    'syncmessage': 'Få nye begivenheder og opdateringer direkte i din kalender.',
    'error': 'Noget gik desværre galt. Prøv igen. Hvis fejlen sker igen skriv til os på',
    'syncing': 'Synkronisere',
    'syncingSubHeading': "Fremadrettet vil du få nye begivenheder og opdateringer i din kalender.",
    'tvSubHeading': "Hvorfor har vi behov for dette? Så vi kan inkludere relevant information i dine påmindelser.",
    'nowShare': 'Del nu',
    "calendarSynced": "Kalender er synkroniseret!",
    "recommendations": "Anbefalinger",
    "syncGetEvents": "Synkroniser for at få begivenheder og opdateringer direkte i din kalender.",
    "syncCalendarWith": "Synkroniser kalender med",
    "customizeCalendar": "Individualiser din kalender",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "Spring over",
    "next": "Næste",
    "syncWith": "Synkroniser med",
    "getNewEvents": "Få nye begivenheder og opdateringer direkte i din kalender"
  },
  'chinesesimplified': {
    'select': '选您的日历',
    'scroll': '向下滚动看更多',
    'other': '其他',
    'open': '打开',
    'calendar': '日历',
    'clickactions': '点击',
    'clicksubscribe': '点击订阅其他日历',
    'enterlink': '输入以下网址，然后点击继续',
    'eventtimeswrong': '活动时间不对？确认您的',
    'timezone': '时区设置',
    'clickyes': '在弹出窗口点击 Yes!',
    'ifnopopup': '没有弹出窗口，点击',
    'clickopen': '点击打开日历选从网上。',
    'enterlink2': '输入以下网址，然后点击 OK。',
    'torefresh': '刷新日历: 点击 Send/Recieve 标签然后点击 Send/Refresh All Folders',
    'clicklaunch': '在弹出窗口点击 Launch!',
    'clickfile': '点击 File ',
    'clicknew': '点击 New Calendar Subscription。。。 ',
    'enterlink3': '输入以下网址，然后点击订阅。',
    'savecalendar': '保存日历.',
    'opencalendar': '打开日历',
    'tokeepadding': '要不断加所有活动到日历，输入你的email在下。如果加活动到不同日历，跳过这一步。',
    'validemail': '请输入一个正确的email。',
    'submit': '输入',
    'dontsee': '在手机看不着？到',
    'mobilebrowser': '在你的手机浏览器，并确保，',
    'calendarchecked': '日历选到了',
    'emailme': 'Email 我这些步骤',
    'poweredby': '赞助',
    'allsports': '所有体育项目',
    'selectyour': '选你的',
    'stillproblems': '还有问题？',
    'troubleshoot': '排查',
    'welldone': '很好！',
    'addtocalendar': '加到日历',
    'allcategories': '所有类别',
    'choosecategory': '选类别',
    'syncyahoo': '跟Yahoo同步',
    'calendardownloaded': '下载了日历',
    'followinstructions': '按照这些步骤',
    'staticdownload': '这是一次性下载。想同步请在前一屏幕选项。',
    'share': '分享',
    'added': '加到了日历！',
    'view': '现在看。',
    'copy': '拷贝网址',
    'also': '还有看',
    'downloadcalendar': '下载日历',
    'adding': '正在加到你的',
    'download': '下载',
    'upcoming': '查看以后的活动',
    'sync': '同步跟',
    'syncmessage': '收到新的活动和更新在你的日历',
    'error': '抱歉出了事故。再试一次。如果还有事故，请email我们在',
    'syncing': '正在同步',
    'syncingSubHeading': "以后，你会在有新的活动和更新到你的日历",
    'tvSubHeading': "为什么需要这个？应为可以加正确的台在你的日历",
    'nowShare': '现在分享',
    "calendarSynced": "日历同步了！",
    "recommendations": "其他建议",
    "syncGetEvents": "请同步得到活动和更新在你的日历",
    "chooseCalendar": "选一个日历",
    "syncCalendarWith": "同步跟",
    "customizeCalendar": '定制你的日历',
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "跳过",
    "next": "下一步",
    "syncWith": "同步和",
    "getNewEvents": "收到新的活动和更新在你的日历"
  },
  'chinesetraditional': {
    'select': '選您的日曆',
    'scroll': '向下滾動看更多',
    'other': '其他',
    'open': '打開',
    'calendar': '日曆',
    'clickactions': '點擊',
    'clicksubscribe': '點擊訂閱其他日曆',
    'enterlink': '輸入以下網址，然後點擊繼續',
    'eventtimeswrong': '活動時間不對？確認您的',
    'timezone': '時區設置',
    'clickyes': '在彈出窗口點擊 Yes！',
    'ifnopopup': '沒有彈出窗口，點擊',
    'clickopen': '點擊打開日曆選從網上。',
    'enterlink2': '輸入以下網址，然後點擊 OK。',
    'torefresh': '刷新日曆: 點擊 Send/Receive 標籤然後點擊 Send/Refresh All Folders',
    'clicklaunch': '在彈出窗口點擊 Launch！',
    'clickfile': '點擊 File',
    'clicknew': '點擊 New Calendar Subscription。。。',
    'enterlink3': '輸入以下網址，然後點擊訂閱。',
    'savecalendar': '保存日曆.',
    'opencalendar': '打開日曆',
    'tokeepadding': '要不斷加所有活動到日曆，輸入你的email在下。如果加活動到不同日曆，跳過這一步。',
    'validemail': '請輸入一個正確的email.',
    'submit': '輸入',
    'dontsee': '在手機看不著？到',
    'mobilebrowser': '在你的手機瀏覽器，並確保，',
    'calendarchecked': '日曆選到了',
    'emailme': 'Email 我這些步驟',
    'poweredby': '贊助',
    'allsports': '所有體育項目',
    'selectyour': '選你的',
    'stillproblems': '還有問題？',
    'troubleshoot': '排查',
    'welldone': '很好！',
    'addtocalendar': '加到日曆',
    'allcategories': '所有類別',
    'choosecategory': '選類別',
    'syncyahoo': '跟Yahoo同步',
    'calendardownloaded': '下載了日曆',
    'followinstructions': '按照這些步驟',
    'staticdownload': '這是一次性下載。想同步請在前一屏幕選項。',
    'share': '分享',
    'added': '加到了日曆！',
    'view': '現在看。',
    'copy': '拷貝網址',
    'also': '還有看',
    'downloadcalendar': '下載日曆',
    'adding': '正在加到你的',
    'download': '下載',
    'upcoming': '查看以後的活動',
    'sync': '同步跟',
    'syncmessage': '收到新的活動和更新在你的日曆',
    'error': '抱歉出了事故。再試一次。如果還有事故，請email我們在',
    'syncing': '正在同步',
    'syncingSubHeading': "以後，你會在有新的活動和更新到你的日曆",
    'tvSubHeading': "为什么需要这个？应为可以加正确的台在你的日历",
    'nowShare': '現在分享',
    "calendarSynced": "日曆同步了！",
    "recommendations": "其他建議",
    "syncGetEvents": '請同步得到活動和更新在你的日曆',
    "chooseCalendar": "選一個日曆",
    "syncCalendarWith": "同步跟",
    "customizeCalendar": '定制你的日曆',
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": '跳過',
    "next": "下一步",
    "syncWith": "同步和",
    "getNewEvents": "收到新的活動和更新在你的日曆"
  },
  "catalan": {
    'select': 'Selecciona el teu calendari',
    'scroll': 'Mira avall per veure més',
    'other': 'Altres',
    'open': 'Obre',
    'calendar': 'Calendari',
    'clickactions': 'Clics',
    'clicksubscribe': 'Clica a Subscriure\'s a Altres Calendaris',
    'enterlink': 'Entra l\'enllaç a sota, després clica Continuar',
    'eventtimeswrong': 'Hi ha error en els horaris? Verifica el teu',
    'timezone': 'configuració de la zona horària',
    'clickyes': 'Fes clic a Sí a la finestra emergent',
    'ifnopopup': 'Si no s\'obre una finestra, obre',
    'clickopen': 'Fes clic a Obrir Calendari i selecciona\'l d\'internet',
    'enterlink2': 'Escriu el linc a sota, llavors fes clic a OK',
    'torefresh': 'Per refrescar el calendari: fes clic a la pestanya Envia/Rep i a Envia/rep totes les carpetes',
    'clicklaunch': 'Fes clic a Afegeix en la finestra emergent!',
    'clickfile': 'Clica Arxiu',
    'clicknew': 'Clica a Subscripció a un nou calendari',
    'enterlink3': 'Entra l\'enllaç a sota, després clica Subscriure\'s',
    'savecalendar': 'Desa el calendari.',
    'opencalendar': 'Obre el calendari.',
    'tokeepadding': 'Per seguir afegint esdeveniments al mateix calendari, entra el teu e-mail a sota. Salta\'t aquest pas si t\'està bé tenir afegir esdeveniments a diferents calendaris',
    'validemail': 'Si us plau, entra una adreça de correu electrònic vàlida.',
    'submit': 'Envia',
    'dontsee': 'No ho veus al teu mòbil? Vés-hi',
    'mobilebrowser': 'al teu navegador per a mòbils i assegura-te\'n',
    'calendarchecked': 'el calendari ha estat comprovat',
    'emailme': 'Correu electrònic i instruccions',
    'poweredby': 'Impulsat per',
    'allsports': 'Tots els esports',
    'selectyour': 'Selecciona el teu',
    'stillproblems': 'Encara tens problemes?',
    'troubleshoot': 'Registre de problemes',
    'welldone': 'Ben fet!',
    'addtocalendar': 'Afegeix al calendari',
    'allcategories': 'Totes les categories',
    'choosecategory': 'Tria una categoria',
    "chooseCalendar": "Tria un calendari",
    'syncyahoo': 'Sincronitza amb Yahoo',
    'calendardownloaded': 'Aquest calendari ha estat descarregat',
    'followinstructions': 'Segueix les instruccions',
    'staticdownload': 'Aquesta és una descàrrega estàtica. Per sincronitzar, tria una de les altres opcions de la pantalla anterior',
    'share': 'Compartit',
    'added': 'El calendari ha estat afegit!',
    'view': 'MIRA-HO ARA',
    'copy': 'COPIA L\'ENLLAÇ',
    'also': 'Comprova-ho, també',
    'downloadcalendar': 'DESCARREGA EL CALENDARI',
    'adding': 'Afegint al teu',
    'download': 'Descarrega el',
    'upcoming': 'Visualitza els propers esdeveniments',
    'sync': 'Sincronitza amb',
    'syncmessage': 'Rep els nous esdeveniments i actualitzacions directament al teu calendari',
    'error': 'Desafortunadament, alguna cosa no ha anat bé. Torna-ho a intentar. Si el problema persisteix, envia\'ns un correu a',
    'syncing': 'Sincronització',
    'syncingSubHeading': "De cara al futur , obtindrà nous esdeveniments i actualitzacions en el seu calendari",
    'tvSubHeading': "Per què necessitem això ? Així que podem incloure la informació del canal dret en els teus recordatoris.",
    'nowShare': 'ara compartir',
    "calendarSynced": "Calendari Sincronitzat!",
    "recommendations": "Recomanacions",
    "syncGetEvents": 'Sincronitzar per obtenir esdeveniments i actualitzacions directament al seu calendari',
    "syncCalendarWith": "Calendar Sincronitzar Amb",
    "customizeCalendar": 'Personalitza el teu Calendari',
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": 'Ometa',
    "next": "Següent",
    "syncWith": "Sincronitzar amb",
    "getNewEvents": "Obtenir nous esdeveniments i actualitzacions directament al seu calendari"
  },
  "korean": {
    'select': "캘린더를 선택하세요.",
    'scroll': "더 보려면 아래로 스크롤하세요.",
    'other': "다른",
    'open': "열기",
    'calendar': "캘린더",
    'clickactions': "동작 선택",
    'clicksubscribe': "다른 캘린더 구독하기'를 클릭하세요.",
    'enterlink': "아래의 링크를 입력하고 '계속하기'를 클릭하세요.",
    'eventtimeswrong': "이벤트 시간이 잘못되었나요? 을(를) 인증하세요.",
    'timezone': "시간대 설정",
    'clickyes': "팝업창에서 '네'를 클릭하세요.",
    'ifnopopup': "팝업창이 나타나지 않는 경우, 을(를) 여세요.",
    'clickopen': "캘린터 열기를 클릭하고 '인터넷에서' 를 선택하세요.",
    'enterlink2': "아래의 링크를 입력하고 '확인'을 클릭하세요.",
    'torefresh': "캘린더를 새로 고치려면 '보내기/받기' 탭을 클릭한 후 '모든 폴더 보내기/받기'를 클릭하세요.",
    'clicklaunch': "팝업창에서 '설치'를 클릭하세요.",
    'clickfile': "파일'을 클릭하세요.",
    'clicknew': "새 캘린더 구독'을 클릭하세요.",
    'enterlink3': "아래의 링크를 입력하고 '구독하기'를 클릭하세요.",
    'savecalendar': "캘린더 저장",
    'opencalendar': "캘린더 열기",
    'tokeepadding': "같은 캘린더에 모든 이벤트를 저장하려면 아래에 이메일을 입력하세요. 서로 다른 캘린더에 이벤트에 저장하고자 하는 경우, 이 단계를 건너뛰셔도 됩니다.",
    'validemail': "사용 가능한 이메일을 입력하세요.",
    'submit': "제출",
    'dontsee': "핸드폰에서 보이지 않나요? (으)로 가세요.",
    'mobilebrowser': "모바일 브라우저로 이동해서",
    'calendarchecked': "캘린더에 체크했는지 확인하세요.",
    'emailme': "이 안내문을 이메일로 보내주세요.",
    'poweredby': "에 의해 구동",
    'allsports': "스포츠를",
    'selectyour': "을(를) 선택하세요.",
    'stillproblems': "아직도 문제가 있나요?",
    'troubleshoot': "문제 해결",
    'welldone': "해결되었습니다!",
    'addtocalendar': "캘린더에 추가",
    'allcategories': "모든 카테고리",
    'choosecategory': "카테고리 선택",
    'syncyahoo': "Yahoo와 연동",
    'calendardownloaded': "이 캘린더를 이미 다운로드했습니다.",
    'followinstructions': "다음 안내를 따르세요.",
    'staticdownload': "일반 다운로드입니다. 동기화하려면 이전 화면에서 다른 사항을 선택하세요.",
    'share': "공유",
    'added': "캘린더가 추가되었습니다!",
    'view': "지금 보기",
    'copy': "링크 복사",
    'also': "도 확인해보세요.",
    'downloadcalendar': "캘린더 다운로드",
    'adding': "에 추가",
    'download': "을(를) 다운로드",
    'upcoming': "예정된 이벤트 보기",
    'sync': "와(과) 동기화",
    'syncmessage': "새 이벤트를 찾아 캘린더에 바로 업데이트하세요.",
    'error': "문제가 발생했습니다. 다시 시도하세요. 계속 문제가 발생하는 경우, (으)로 이메일을 보내주세요.",
    'syncing': "동기화 중",
    'syncingSubHeading': "앞으로는 캘린더에 새 이벤트와 업데이트를 받으시게 됩니다.",
    'tvSubHeading': "왜 필요하냐구요? 리마인더에 정확한 채널 정보를 제공해드리기 위해서입니다. ",
    'nowShare': "이제 (을)를 공유하세요.",
    'calendarSynced': "캘린더가 동기화되었습니다!",
    'recommendations': "추천",
    'syncGetEvents': "이벤트와 업데이트를 캘린더로 받아보려면 동기화하세요.",
    'chooseCalendar': "캘린더 선택",
    'syncCalendarWith': "와(과) 동기화하세요.",
    'customizeCalendar': "캘린더를 사용자 설정하세요.",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    'skip': "건너뛰기",
    'next': "다음",
    'syncWith': "와 동기화",
    'getNewEvents': "캘린더 에 직접 새로운 이벤트와 업데이트를",
  },
  "turkish": {
    'select': "Takvimini seç",
    'scroll': "Daha fazlası için asağı tıkla ",
    'other': "Diğer",
    'open': "Aç",
    'calendar': "Takvim",
    'clickactions': "hareketlere tıkla",
    'clicksubscribe': "Başka takvimlere üyelik için tıkla",
    'enterlink': "Aşağıdaki bağlantıyı girin, ardından Devam düğmesini tıklatın.",
    'eventtimeswrong': "Olay kere yanlış ? Senin doğrulayın",
    'timezone': "zaman dilimi ayarları",
    'clickyes': "Açılan üzerine Evet'i!",
    'ifnopopup': "Bir şey belirirse ' açık",
    'clickopen': "Açık Takvim tıklayın ve Internet From seçin",
    'enterlink2': "Aşağıdaki bağlantıyı girin, sonra Tamam'ı tıklayın.",
    'torefresh': "Takvimi yenilemek için : Gönder / gönderilmesini talep sekmesini alın ve tıklayın / Tüm Klasörleri Alma",
    'clicklaunch': "Açılan üzerine Başlat tıklayın!",
    'clickfile': "Dosya tıklayın",
    'clicknew': "Yeni Takvim Abonelik tıklayınız ...",
    'enterlink3': "Aşağıdaki bağlantıyı girin, ardından Abone tıklatın.",
    'savecalendar': "Takvim kaydedin.",
    'opencalendar': "Açık takvim.",
    'tokeepadding': "Aynı takvime tüm etkinlikleri eklemeye devam etmek, aşağıya e-postanızı girin. Ayrı takvimlere ekleyerek olayları sahip iyiyiz bu adımı atlayın.",
    'validemail': "Geçerli bir e-posta girin.",
    'submit': "Gönder",
    'dontsee': "Telefonunuzda görmüyorum ? Git",
    'mobilebrowser': "Mobil tarayıcı ve emin üzerinde",
    'calendarchecked': "Takvim kontrol edilir",
    'emailme': "Bana bu talimatları e-posta",
    'poweredby': "Tarafından desteklenmektedir",
    'allsports': "Tüm Spor",
    'selectyour': "Sizin yanınızdaki seçin",
    'stillproblems': "Hala sorun yaşıyorsanız?",
    'troubleshoot': "Giderme",
    'welldone': "Aferin!",
    'addtocalendar': "Takvime Ekle",
    'allcategories': "Tüm Kategoriler",
    'choosecategory': "Kategori Seç",
    'syncyahoo': "Yahoo! ile senkronize",
    'calendardownloaded': "Bu takvim indirildi ",
    'followinstructions': "Bu talimatları takip et",
    'staticdownload': "Bu statik bir indirmektir. Senkronizasyon için , önceki ekrana gelen diğer seçeneklerden birini seçiniz.",
    'share': "Paylaş",
    'added': "Takvim eklendi!",
    'view': "Şimdi bak",
    'copy': "Linki kopyala",
    'also': "Ayrıca , bakmak:",
    'downloadcalendar': "INDIR TAKVIM",
    'adding': "Eklemek",
    'download': "Indir",
    'upcoming': "Yaklaşan etkinlikleri görmek",
    'sync': "Ile senkronize",
    'syncmessage': "Doğrudan yeni olaylar ve güncellemeleri takviminde alın.",
    'error': "Ne yazık ki, bir şeyler ters gitti. Tekrar dene. Bu devam ederse , bize bir e-posta",
    'syncing': "Senkronize",
    'syncingSubHeading': "İleriye yönelik olarak, size takvimde yeni olaylar ve güncellemeleri alırsınız.",
    'tvSubHeading': "Buna neden ihtiyacımız var? Bu yüzden hatırlatıcı doğru kanal bilgisini içerebilir.",
    'nowShare': "Şimdi paylaş",
    'calendarSynced': "Takvim Senkronize!",
    'recommendations': "Öneriler",
    'syncGetEvents': "Sync takviminde doğrudan olayları ve güncelleştirmeleri almak için.",
    'chooseCalendar': "Bir takvim seçin",
    'syncCalendarWith': "Ile Sync Takvim",
    'customizeCalendar': "Sizin Takvim Özelleştirme",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    'skip': "Geç",
    'next': "Sıradaki",
    'syncWith': "Ile senkronize",
    'getNewEvents': "Takviminize doğrudan yeni olaylar ve güncellemelerini alın",
  },
  "spanish": {
    'select': "Seleccione su calendario",
    'scroll': "Desplácese hacia abajo para ver más",
    'other': "Otro",
    'open': "Abierto",
    'calendar': "Calendario",
    'clickactions': "Haga clic en Acciones",
    'clicksubscribe': "Haga clic en suscribirse a otros calendarios",
    'enterlink': "Escriba el siguiente enlace, haga clic en Continuar.",
    'eventtimeswrong': "Horario de los eventos mal? Verifica tu",
    'timezone': "configuración de zona horaria",
    'clickyes': "Haga clic en Sí en la ventana emergente!",
    'ifnopopup': "Si no aparece la ventana emergente, abierta",
    'clickopen': "Haga clic en Abrir Calendario y seleccione De Internet.",
    'enterlink2': "Escriba el siguiente enlace , haga clic en Aceptar.",
    'torefresh': "Para actualizar el calendario: haga clic en Enviar / Recibir ficha y haga clic en Enviar / Recibir Todas las Carpetas",
    'clicklaunch': "Haga clic en Iniciar en la ventana emergente!",
    'clickfile': "Haga clic en Archivo",
    'clicknew': "Haga clic en Nuevo Calendario suscripción ...",
    'enterlink3': "Escriba el siguiente enlace , haga clic en Suscribir.",
    'savecalendar': "Guarde el calendario.",
    'opencalendar': "Abra el calendario.",
    'tokeepadding': "Para seguir sumando todos los eventos en la misma nota, ingrese su correo electrónico debajo. Omita este paso si estás bien con tener eventos añadiendo a calendarios separados.",
    'validemail': "Por favor introduzca una dirección de correo electrónico válida.",
    'submit': "Enviar",
    'dontsee': "No verlo en su teléfono ? Ir a",
    'mobilebrowser': "en su navegador móvil y asegúrese",
    'calendarchecked': "el calendario está marcado",
    'emailme': "Email me estas instrucciones",
    'poweredby': "Alimentado por",
    'allsports': "Todos los Deportes",
    'selectyour': "Selecciona tu",
    'stillproblems': "Todavía tiene problemas?",
    'troubleshoot': "Solucionar",
    'welldone': "¡Bien hecho!",
    'addtocalendar': "Agregar al Calendario",
    'allcategories': "Todas las Categorias",
    'choosecategory': "Elige una Categoría",
    'chooseCalendar': "Elija un calendario",
    'syncyahoo': "Sincronización con Yahoo",
    'calendardownloaded': "Este calendario se ha descargado",
    'followinstructions': "Siga estas instrucciones",
    'staticdownload': "Esta es una descarga estática. Para la sincronización , elija una de las otras opciones en la pantalla anterior.",
    'share': "Compartir",
    'added': "Calendario ha sido añadido!",
    'view': "VER AHORA",
    'copy': "Copiar hipervínculo",
    'also': "También, busque en",
    'downloadcalendar': "Descargar el calendario",
    'adding': "Agregando a tu",
    'download': "Descargue la",
    'upcoming': "Ver los eventos futuros",
    'sync': "Sincronización con",
    'syncmessage': "Obtener nuevos eventos y actualizaciones directamente en su calendario.",
    'error': "Por desgracia , algo salió mal . Inténtalo de nuevo. Si esto persiste, envíenos un correo electrónico a",
    'syncing': "Sincronización",
    'syncingSubHeading': "De cara al futuro , obtendrá nuevos eventos y actualizaciones en su calendario.",
    'tvSubHeading': "¿Porqué necesitamos esto? Así que podemos incluir la información del canal derecho en tus recordatorios.",
    'nowShare': "ahora compartir",
    'calendarSynced': "Calendario Sincronizado!",
    'recommendations': "Recomendaciones",
    'syncGetEvents': "Sincroniza para obtener eventos y actualizaciones directamente en su calendario.",
    'syncCalendarWith': "Sincroniza Calendario Con",
    'customizeCalendar': "Personaliza tu calendario",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    'skip': "Saltar",
    'next': "Siguiente",
    'syncWith': "Sincroniza con",
    'getNewEvents': "Obtener nuevos eventos y actualizaciones directamente en su calendario",
  },
  "norwegian": {
    'select': 'Select Your Calendar',
    'scroll': 'Scroll down to see more',
    'other': 'Other',
    'open': 'Open',
    'calendar': 'Calendar',
    'clickactions': 'Click Actions',
    'clicksubscribe': 'Click Subscribe to Other Calendars',
    'enterlink': 'Enter the link below, then click Continue.',
    'eventtimeswrong': 'Event times wrong? Verify your',
    'timezone': 'timezone settings',
    'clickyes': 'Click Yes on the popup!',
    'ifnopopup': 'If no popup appears, open',
    'clickopen': 'Click Open Calendar and select From Internet.',
    'enterlink2': 'Enter the link below, then click Ok.',
    'torefresh': 'To refresh the calendar: click on Send/Receive tab and click Send/Receive All Folders',
    'clicklaunch': 'Click Launch on the popup!',
    'clickfile': 'Click File',
    'clicknew': 'Click New Calendar Subscription...',
    'enterlink3': 'Enter the link below, then click Subscribe.',
    'savecalendar': 'Save calendar.',
    'opencalendar': 'Open calendar.',
    'tokeepadding': 'To keep adding all events to the same calendar, enter your email below. Skip this step if you\'re fine with having events adding to separate calendars.',
    'validemail': 'Please enter a valid email.',
    'submit': 'Submit',
    'dontsee': 'Don\'t see it on your phone? Go to',
    'mobilebrowser': 'on your mobile browser and make sure',
    'calendarchecked': 'the calendar is checked',
    'emailme': 'Email me these instructions',
    'poweredby': 'Powered By',
    'allsports': 'All Sports',
    'selectyour': 'Select your',
    'stillproblems': 'Still having problems?',
    'troubleshoot': 'Troubleshoot',
    'welldone': 'Well Done!',
    'addtocalendar': 'Add to Calendar',
    'allcategories': 'All Categories',
    'choosecategory': 'Choose a Category',
    "chooseCalendar": "Choose a Calendar",
    'syncyahoo': 'Sync With Yahoo',
    'calendardownloaded': 'This calendar has been downloaded',
    'followinstructions': 'Follow these instructions',
    'staticdownload': 'This is a static download. For syncing, please choose one of the other options from the previous screen.',
    'share': 'Share',
    'added': 'Calendar has been added!',
    'view': 'VIEW NOW',
    'copy': 'COPY LINK',
    'also': 'Also, Check out:',
    'downloadcalendar': 'DOWNLOAD CALENDAR',
    'adding': 'Adding to your',
    'download': 'Download the',
    'upcoming': 'View Upcoming Events',
    'sync': 'Sync with',
    'syncmessage': 'Get new events and updates directly in your calendar.',
    'error': 'Oops, something went wrong. Try again. If this persists, shoot us an email at',
    'syncing': 'Syncing',
    'syncingSubHeading': "Going forward, you'll get new events and updates in your calendar.",
    'tvSubHeading': "Why do we need this? So we can include the right channel information in your reminders.",
    'nowShare': 'now share',
    "calendarSynced": "Calendar Synced!",
    "recommendations": "Stanza Recommends",
    "syncGetEvents": "Sync to get events and updates directly in your calendar.",
    "syncCalendarWith": "Sync Calendar With",
    "customizeCalendar": "Customize Your Calendar",
    "localizeYourCalendar": "Localize Your Calendar",
    'geoSubHeading': "Why do we need this? So you can only sync to the events around you.",
    "skip": "SKIP",
    "next": "NEXT",
    "syncWith": "Sync with",
    "getNewEvents": "Get new events and updates directly in your calendar"
  },
  "japanese": {
    added: "カレンダーが追加されました！",
    adding: "に追加",
    addtocalendar: "カレンダーに追加",
    allcategories: "すべてのカテゴリ",
    allsports: "すべてのスポーツ",
    also: "こちらもオススメです",
    calendar: "[カレンダー]",
    calendarSynced: "カレンダーが同期されました！",
    calendarchecked: "カレンダーがチェックされていることを確認してください",
    calendardownloaded: "このカレンダーがダウンロードされています",
    chooseCalendar: "カレンダーを選択",
    choosecategory: "カテゴリを選択",
    clickactions: "[アクション]をクリックします",
    clickfile: "[ファイル]をクリックしてください",
    clicklaunch: "ポップアップの[起動]をクリックしてください。",
    clicknew: "[新しいカレンダーの購読]をクリックして...",
    clickopen: "[カレンダーを開く]をクリックして、[インターネットから]を選択してください。",
    clicksubscribe: "[他のカレンダーを購読する]をクリックします",
    clickyes: "ポップアップで[はい]をクリックしてください!",
    copy: "リンクのコピー",
    customizeCalendar: "あなたのカレンダーをカスタマイズします",
    dontsee: "お使いの携帯電話で見れない場合は、次へアクセスしてください",
    download: "ダウンロード：",
    downloadcalendar: "カレンダーのダウンロード",
    emailme: "これらの手順をメールアドレスにも送ります",
    enterlink: "以下のリンクを入力し、 [続行]をクリックします。",
    enterlink2: "以下のリンクを入力し、 [OK]をクリックします。",
    enterlink3: "下記のリンクを入力し、 [登録]をクリックします。",
    error: "残念ながら問題が起きました。再試行してください。解決しない場合は、次までメールを送信してください。",
    eventtimeswrong: "イベント時間が間違っていませんか？確認してください",
    followinstructions: "これらの指示に従ってください。",
    geoSubHeading: "Why do we need this? So you can only sync to the events around you.",
    getNewEvents: "あなたのカレンダーに直接、新しいイベントや最新情報が更新されます。",
    ifnopopup: "ポップアップが表示されない場合は、次を開きます",
    localizeYourCalendar: "Localize Your Calendar",
    mobilebrowser: "お使いの携帯電話で見れない場合は、次へアクセスしてください",
    next: "次",
    nowShare: "今すぐシェア",
    open: "[開く]",
    opencalendar: "カレンダーを開きます。",
    other: "[その他]",
    poweredby: "搭載",
    recommendations: "オススメ",
    savecalendar: "カレンダーを保存します。",
    scroll: "もっと表示するには、下にスクロールします。",
    select: "[あなたのカレンダー]を選択します。",
    selectyour: "選択してください",
    share: "シェア",
    skip: "スキップ",
    staticdownload: "これは静的なダウンロードです。同期するには、前の画面にもどり他のオプションを選択してください。",
    stillproblems: "まだ問題がありますか？",
    submit: "送信",
    sync: "と同期",
    syncCalendarWith: "とカレンダーを同期する：",
    syncGetEvents: "あなたのカレンダーに直接、新しいイベントや最新情報が更新されるよう、同期します。",
    syncWith: "と同期",
    syncing: "同期中",
    syncingSubHeading: "今後、あなたのカレンダーに新しいイベントや最新情報が更新されます。",
    syncmessage: "あなたのカレンダーに直接、新しいイベントや最新情報が更新されます。",
    syncyahoo: "Yahooと同期",
    timezone: "タイムゾーンの設定を確認します",
    tokeepadding: "同じカレンダーにすべてのイベントを追加し続けるためには、下にメールアドレスを入力してください。別々のカレンダーへのイベント追加で問題ない場合は、このステップをスキップしてください。",
    torefresh: "カレンダーを更新するには： [送信/受信]タブ、[すべてのフォルダを送信/受信]の順にクリックします。",
    troubleshoot: "トラブルシューティング",
    tvSubHeading: "あなたにぴったりの情報をお届けできるようになります。",
    upcoming: "近日に予定しているイベントを見ます。",
    validemail: "正しいメールアドレスを入力してください。",
    view: "表示する",
    welldone: "上出来！"
  },
}